version: '3.7'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432